---

- hosts: all
  become: yes
  tasks:
  - name: Add ansible user
    user:
      name: ansible
  - name: Give ansible sudoer privilege
    lineinfile:
      dest: /etc/sudoers
      state: present
      line: "ansible ALL=(ALL) NOPASSWD:ALL"

- hosts: all
  become: yes
  roles:
    - { role: ssh-keys, tags: ['ssh-keys'] }

- hosts: all
  become: yes
  tasks:
  - name: Disable ssh root login
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      line: "PermitRootLogin no"
      regexp: "^PermitRootLogin.*"

- hosts: all
  become: yes
  tasks:
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
      enabled: yes
